service: auto-deploy-lambda
provider:
  name: aws
  region: ap-northeast-1
  timeout: 120

  environment:
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

functions:
  slack:
    handler: src/index.ts
    description: "Post message to Slack"
    timeout: 60
