name: Report

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - run: |
          to="$(date "+%Y-%m-%dT%H:%M:%S")"
          from="$(date "+%Y-%m-%dT%H:%M:%S" -d '1 day ago')"
          script='query {
            user(login: \"'${USERNAME}'\") {
              contributionsCollection(from: \"'$from'\", to:\"'$to'\") {
                totalCommitContributions
              }
            }
          }'
          script="$(echo $script)"

          dailyCommitContributions="$(curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -X POST -d "{ \"query\": \"$script\" }" https://api.github.com/graphql \
            | jq '.["data"]["user"]["contributionsCollection"]["totalCommitContributions"]')"

          echo $dailyCommitContributions
