name: Report

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - run: |
          to="$(date -u　"+%Y-%m-%dT00:00:00")"
          from="$(date -u　"+%Y-%m-%dT00:00:00" -d '1 day ago')"
          echo $to $from
          script='query {
            user(login: \"'${USERNAME}'\") {
              contributionsCollection(from: \"'$from'\", to:\"'$to'\") {
                totalCommitContributions
              }
            }
          }'
          script="$(echo $script)"

          dailyCommitContributions="$(curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -X POST -d "{ \"query\": \"$script\" }" https://api.github.com/graphql \
            | jq '.["data"]["user"]["contributionsCollection"]["totalCommitContributions"]')"

          if [ "$dailyCommitContributions" -eq "0" ]; then
            curl -X POST -H "Content-type: application/json" --data "{\"text\":\"今日はまだ草が生えていません\"}" "${WEBHOOK_URL}"
          else
            echo "Already ${USERNAME} has $dailyCommitContributions contributions today!"
            exit 0
          fi
