name: Report

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - run: |
          to="$(date "+%Y-%m-%dT%H:%M:%S")"
          from="$(date "+%Y-%m-%dT%H:%M:%S" -d '1 day ago')"
          script='query {
            user(login: \"nacal\") {
              contributionsCollection(from: \"'$from'\", to:\"'$to'\") {
                totalCommitContributions
              }
            }
          }'
          script="$(echo $script)"

          variables='{
            "name": "nacal",
            "from":"2021-10-18T00:00:00",
            "to":"2021-10-19T00:00:00"
          }'
          variables="$(echo $variables)"

          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -X POST -d "{ \"query\": \"$script\", \"variables\": \"$variables\" }" https://api.github.com/graphql \
            | jq .
